import ProfileExample from "@assets/profileExample.png";

export const partTimeDummyData = [
  {
    id: 1,
    title: "여성분 중 친구인 척 해줄 사람!! 제바류ㅠ",
    content:
      "부모님이 여자친구 있다고 해서요. 급히 친구인 척 해줄 분 찾습니다. 제발 도와주세요!",
    writer: "몰래외박장인",
    profileImage: ProfileExample,
    createdAt: "17:17",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 3,
    comment: [
      {
        id: 1,
        writer: "친구1",
        profileImage: ProfileExample,
        content: "저 도와드릴게요! 언제 전화하면 될까요?",
      },
      {
        id: 2,
        writer: "친구2",
        profileImage: ProfileExample,
        content: "상황이 급하신가 보네요. 제가 도와드릴게요.",
      },
    ],
  },
  {
    id: 2,
    title: "고등학교 친구인척 해줄사람..!!",
    content:
      "부모님께 고등학교 친구랑 만난다고 했는데, 진짜 친구가 필요해요. 도와주실 분 구해요!",
    writer: "고친구",
    profileImage: ProfileExample,
    createdAt: "14:20",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 10,
    comment: [
      {
        id: 1,
        writer: "동창1",
        profileImage: ProfileExample,
        content: "저랑 고등학교 친구였다고 하면 되나요?",
      },
      {
        id: 2,
        writer: "동창2",
        profileImage: ProfileExample,
        content: "어떤 친구로 할까요? 남자친구? 여자친구?",
      },
    ],
  },
  {
    id: 3,
    title: "이따가 친구인 척하고 전화 좀 대신 받아줄 사람!!",
    content:
      "부모님께 친구랑 같이 있다고 했는데, 대신 전화 받아줄 사람 구해요. 급합니다!",
    writer: "대리전화",
    profileImage: ProfileExample,
    createdAt: "17:17",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 3,
    comment: [
      {
        id: 1,
        writer: "전화친구1",
        profileImage: ProfileExample,
        content: "제가 대신 전화 받아줄게요. 어떤 내용으로 이야기하면 되나요?",
      },
      {
        id: 2,
        writer: "전화친구2",
        profileImage: ProfileExample,
        content: "걱정하지 마세요. 제가 전화 받아드릴게요.",
      },
    ],
  },
  {
    id: 4,
    title: "급구! 친구인 척 대화해줄 사람!!",
    content:
      "급하게 부모님 앞에서 친구인 척 해줄 사람 구해요. 상황이 너무 급해요!",
    writer: "급구",
    profileImage: ProfileExample,
    createdAt: "19:45",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 5,
    comment: [
      {
        id: 1,
        writer: "친구도우미1",
        profileImage: ProfileExample,
        content: "제가 도와드릴게요. 언제 부모님 앞에서 연기하면 되나요?",
      },
      {
        id: 2,
        writer: "친구도우미2",
        profileImage: ProfileExample,
        content: "급하시네요. 저 도와드릴게요.",
      },
    ],
  },
  {
    id: 5,
    title: "부모님께 친구인 척 전화해줄 사람 ㅠㅠ",
    content:
      "부모님께서 확인 전화하신다고 해서요. 친구인 척 전화해주실 분 급히 구합니다.",
    writer: "부모님핑계",
    profileImage: ProfileExample,
    createdAt: "20:10",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 8,
    comment: [
      {
        id: 1,
        writer: "전화도우미1",
        profileImage: ProfileExample,
        content: "제가 전화해드릴게요. 어떤 내용으로 통화하면 되나요?",
      },
      {
        id: 2,
        writer: "전화도우미2",
        profileImage: ProfileExample,
        content: "걱정 마세요. 제가 대신 전화할게요.",
      },
    ],
  },
  {
    id: 6,
    title: "이번 주말 친구인 척 해줄 사람 구해요!!",
    content:
      "이번 주말에 부모님께 친구랑 간다고 했는데, 친구인 척 해주실 분 구합니다.",
    writer: "주말외박러",
    profileImage: ProfileExample,
    createdAt: "21:30",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 12,
    comment: [
      {
        id: 1,
        writer: "주말친구1",
        profileImage: ProfileExample,
        content: "저 주말에 시간 괜찮아요. 친구인 척 해드릴게요.",
      },
      {
        id: 2,
        writer: "주말친구2",
        profileImage: ProfileExample,
        content: "어떤 친구로 하면 될까요? 남자친구? 여자친구?",
      },
    ],
  },
  {
    id: 7,
    title: "급! 외박 핑계 대줄 친구 역할 해줄 분!",
    content:
      "외박하려고 하는데, 부모님께 친구랑 있다고 했어요. 친구 역할 해줄 분 찾습니다!",
    writer: "외박마스터",
    profileImage: ProfileExample,
    createdAt: "22:00",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 7,
    comment: [
      {
        id: 1,
        writer: "외박도우미1",
        profileImage: ProfileExample,
        content: "제가 도와드릴게요. 언제 부모님께 연락하면 될까요?",
      },
      {
        id: 2,
        writer: "외박도우미2",
        profileImage: ProfileExample,
        content: "외박 도우미입니다. 제가 도와드릴게요.",
      },
    ],
  },
  {
    id: 8,
    title: "오늘 밤 친구인 척 같이 있어줄 사람 구합니다",
    content:
      "오늘 밤에 부모님께 친구랑 있다고 했어요. 같이 있어줄 사람 구합니다.",
    writer: "밤외박",
    profileImage: ProfileExample,
    createdAt: "23:15",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 4,
    comment: [
      {
        id: 1,
        writer: "밤도우미1",
        profileImage: ProfileExample,
        content: "저 도와드릴게요. 언제부터 같이 있으면 될까요?",
      },
      {
        id: 2,
        writer: "밤도우미2",
        profileImage: ProfileExample,
        content: "저도 같이 있어줄게요. 걱정 마세요.",
      },
    ],
  },
  {
    id: 9,
    title: "친구인 척 문자 보내줄 분 구해요!",
    content: "부모님께 친구랑 문자한다고 했어요. 대신 문자 보내줄 분 구합니다.",
    writer: "문자도우미",
    profileImage: ProfileExample,
    createdAt: "13:45",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 6,
    comment: [
      {
        id: 1,
        writer: "문자친구1",
        profileImage: ProfileExample,
        content: "제가 문자 대신 보내드릴게요. 어떤 내용으로 보내면 되나요?",
      },
      {
        id: 2,
        writer: "문자친구2",
        profileImage: ProfileExample,
        content: "걱정 마세요. 제가 문자 보내드릴게요.",
      },
    ],
  },
  {
    id: 10,
    title: "부모님께 친구라고 말해줄 사람 급히 구해요!",
    content:
      "부모님께 친구 있다고 했는데, 확인 전화하신대요. 친구라고 말해줄 분 급히 구합니다.",
    writer: "부모님핑계왕",
    profileImage: ProfileExample,
    createdAt: "18:30",
    likeCount: 10,
    isLiked: true,
    unLikeCount: 3,
    isUnLiked: false,
    viewCount: 9,
    comment: [
      {
        id: 1,
        writer: "확인친구1",
        profileImage: ProfileExample,
        content:
          "제가 친구인 척 해드릴게요. 부모님께 어떤 내용으로 이야기하면 되나요?",
      },
      {
        id: 2,
        writer: "확인친구2",
        profileImage: ProfileExample,
        content: "저도 도와드릴게요. 부모님께 뭐라고 말하면 될까요?",
      },
    ],
  },
];
