import { formProps } from "@pages/Editform";
import Hackathon from "./Hackathon.png";
import Farm from "./Farm.png";
import I2024 from "./2024.png";
import Advertise from "./Advertise.png";
import GameJam from "./GameJam.png";

export const forms: formProps[] = [
  {
    name: "Hackathon",
    url: Hackathon,
    user: "PROME",
    visible_height: 200,
    width: 1500,
    height: 750,
    likes: 20,
    texts: [
      {
        name: "장소",
        text: "장소를 입력하세요",
        top: 493,
        left: 210,
        font: 30,
        color: "white",
      },
      {
        name: "날짜",
        text: "일시를 입력하세요",
        top: 565,
        left: 210,
        font: 30,
        color: "white",
      },
    ],
  },
  {
    name: "농활",
    url: Farm,
    visible_height: 500,
    width: 700,
    height: 900,
    user: "user1",
    likes: 13,
    texts: [
      {
        name: "년도",
        text: "년도를 입력하세요",
        top: 42,
        left: 380,
        font: 55,
        color: "white",
      },
      {
        name: "신청기간",
        text: "신청기간를 입력하세요",
        top: 750,
        left: 112,
        font: 20,
        color: "#356F60",
      },
      {
        name: "신청기간",
        text: "신청기간를 입력하세요",
        top: 775,
        left: 112,
        font: 20,
        color: "#356F60",
      },
    ],
  },
  {
    name: "2024년 자유양식",
    url: I2024,
    visible_height: 550,
    width: 700,
    height: 1000,
    user: "user102354",
    likes: 43,
    texts: [
      {
        name: "주제목",
        text: "주제목을 입력하세요",
        top: 560,
        left: 90,
        font: 60,
        color: "#00DC66",
      },
      {
        name: "신청기간",
        text: "신청기간를 입력하세요",
        top: 620,
        left: 90,
        font: 50,
        color: "#B199F8",
      },
      {
        name: "시작날짜(월.일)",
        text: "시작날짜를 입력하세요",
        top: 700,
        left: 130,
        font: 30,
        color: "black",
      },
      {
        name: "종료날짜(월.일)",
        text: "종료날짜를 입력하세요",
        top: 700,
        left: 350,
        font: 30,
        color: "black",
      },
    ],
  },
  {
    name: "무박 2일 광고캠프",
    url: Advertise,
    visible_height: 550,
    width: 700,
    height: 1000,
    user: "user465331",
    likes: 3,
    texts: [
      {
        name: "캠프 일정",
        text: "캠프 일정을 입력하세요",
        top: 820,
        left: 110,
        font: 20,
        color: "white",
      },
      {
        name: "신청 기간",
        text: "신청 기간를 입력하세요",
        top: 869,
        left: 450,
        font: 20,
        color: "white",
      },
    ],
  },
  {
    name: "2024 넥슨 무박 3일 게임잼",
    url: GameJam,
    visible_height: 1000,
    width: 700,
    height: 2300,
    user: "user8754",
    likes: 10,
    texts: [
      {
        name: "모집 기간",
        text: "모집 기간을 입력하세요",
        top: 1442,
        left: 179,
        font: 35,
        color: "black",
      },
      {
        name: "참가자 발표",
        text: "참가자 발표 날짜를 입력하세요",
        top: 1542,
        left: 179,
        font: 35,
        color: "black",
      },
      {
        name: "행사 기간(3일)",
        text: "참가자 발표 날짜를 입력하세요",
        top: 1642,
        left: 179,
        font: 35,
        color: "black",
      },
    ],
  },
];
